---
# defaults file for os_identity-project

project_name: "demo"
domain_ID: "default"
project_desc: "Created by Ansible role:{{ ansible_play_role_names }}, Date created: {{ ansible_date_time.date }}"
