---
# tasks file for outÙ€cluster
- name: uncomment  wsrep_cluster_address
  shell: "sed -i 's/#172.16.105.241,172.16.105.112,172.16.105.65/172.16.105.241,172.16.105.112,172.16.105.65/g' /etc/mysql/conf.d/cluster.cnf"
  tags: uncomment

- name: change safe to bootstrap
  shell: "sed -i 's/safe_to_bootstrap: 1/safe_to_bootstrap: 0/g' /var/lib/mysql/grastate.dat"
  tags: uncomment

- name: comment wsrep_cluster_address
  shell: "sed -i 's/172.16.105.241,172.16.105.112,172.16.105.65/#172.16.105.241,172.16.105.112,172.16.105.65/g' /etc/mysql/conf.d/cluster.cnf" 
  tags: comment

- name: change safe to bootstrap
  shell: "sed -i 's/safe_to_bootstrap: 0/safe_to_bootstrap: 1/g' /var/lib/mysql/grastate.dat"
  tags: comment

- name: restart mariadb                                                                                          
  service: name=mysql enabled=yes state=restarted                                                                
  tags:                                                                                                          
    - comment

- name: wsrep last commit
  shell: mysql -e "show status like 'wsrep_last_committed';"
  tags:
    - comment

