---
# defaults file for mysql_backup
project_name: "backup galera cluster"
path_backup: "/home/"
backup_storage_path: "/home/mysql_backup/"
name_backup_file_infra1: backup_galera_infra1
name_backup_file_infra2: backup_galera_infra2
name_backup_file_infra3: backup_galera_infra3
backup_storage_path: "/home/mysql_backup/"
db_names:
  - cinder
  - keystone
  - neutron
  - nova
  - nova_api
  - nova_cell0
  - placement
  - rally
  - glance

setup_hosts: "openstack-ansible /opt/openstack-ansible/playbooks/setup-hosts.yml"

setup_infrastructure: "openstack-ansible /opt/openstack-ansible/playbooks/setup-infrastructure.yml"
